main:
  project_name: mlops_AHPP_full_pipeline
  experiment_name: dev
  execute_steps:
    - download
    - preprocess
    - segregate
    - check_data
    - neural_network
    #- evaluate
  random_seed: 42
data:
  input_url: "https://drive.google.com/uc?id=16zF4MHEP_bBxAEWpQgVocPupTjRRAgfP"
  reference_dataset: "mlops_AHPP_full_pipeline/train_data.csv:latest"
  sample_dataset: "mlops_AHPP_full_pipeline/test_data.csv:latest"
  ks_alpha: 0.05
  test_size: 0.3
  val_size: 0.3
  stratify: room_type
  target: price
neural_network_pipeline:
  neural_network:
    optimizer: adam
    learning_rate: 1e-2
    epochs: 100
    batch_size: 32
    num_layers: 4
    units: 512
    dropout: 0.5
    kernel_initializer: he_uniform
    batch_normalization: true
    hidden_activation: relu
    output_activation: linear
    loss: 'mae'
    metrics:
      - 'mse'
      - 'mape'
      - 'mae'
    verbose: 1
  numerical_pipe:
    model: 1
  training:
    count: 5
  export_artifact: "model_export"
      
    