name: download_data_eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.5
  - seaborn=0.11.2
  - pandas=1.3.5
  - pip=21.3.1
  - matplotlib=3.5.1
  - pandas-profiling=3.1.0
  - scikit-learn=1.0.2
  - ipywidgets=7.6.5
  - jupyterlab_widgets=1.0.2
  - pip:
      - wandb==0.12.9
      - gdown==4.4.0