name: split_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5
  - pip=21.3.1
  - scikit-learn=1.0.2
  - pip:
      - protobuf==3.20.1
      - wandb==0.12.9
      - gdown==4.4.0